var products = [
    {
      productId: 'PR001',
      productImage: '../assets/cake/Banana and Persimmon Cinnamon Muffins.jpeg',
      productName: 'Banana and Persimmon Cinnamon Muffins',
      productPrice: 40000,
      productDescription: 'Flavors of banana, persimmon, and cinnamon in our moist and fluffy muffins.',
      productCategory: 'Cake',
    },
    {
      productId: 'PR002',
      productImage: '../assets/cake/Buttery Cinnamon Cake.jpg',
      productName: 'Buttery Cinnamon Cake',
      productPrice: 35000,
      productDescription: 'Experience the exquisite blend of premium ingredients like creamy butter and aromatic cinnamon in our Buttery Cinnamon Cake.',
      productCategory: 'Cake',
    },
    {
      productId: 'PR003',
      productImage: '../assets/cake/Cinnamon and Amaretto Pound Cake.png',
      productName: 'Cinnamon and Amaretto Pound Cake',
      productPrice: 95000,
      productDescription: 'Made with premium ingredients including aromatic cinnamon and the delicate essence of amaretto.',
      productCategory: 'Cake',
    },
    {
      productId: 'PR004',
      productImage: '../assets/cake/Cinnamon Coffee Cake.jpg',
      productName: 'Cinnamon Coffee Cake',
      productPrice: 55000,
      productDescription: 'Made with a tantalizing blend of ingredients that include aromatic cinnamon, rich butter, and a delightful streusel topping.',
      productCategory: 'Cake',
    },
    {
      productId: 'PR005',
      productImage: '../assets/cake/Cinnamon Swirl Bundt Coffee Cake.jpg',
      productName: 'Cinnamon Swirl Bundt Coffee Cake',
      productPrice: 95000,
      productDescription: 'Featuring a delightful combination of ingredients like aromatic cinnamon, moist cake batter, and a mouthwatering swirl of sweet goodness.',
      productCategory: 'Cake',
    },
    {
      productId: 'PR006',
      productImage: '../assets/cake/Cinnamon Mocha Sheet Cake.jpg',
      productName: 'Cinnamon Mocha Sheet Cake',
      productPrice: 35000,
      productDescription: 'Delivers a luscious combination of warm spice and velvety chocolate, creating a dessert that is both comforting and decadent.',
      productCategory: 'Cake',
    },
    {
      productId: 'PR007',
      productImage: '../assets/cookie/Anise Icebox Cookies.jpg',
      productName: 'Anise Icebox Cookies',
      productPrice: 45000,
      productDescription: 'Crafted with a perfect combination of ingredients including aromatic anise extract, buttery dough, and a hint of vanilla.',
      productCategory: 'Cookie',
    },
    {
      productId: 'PR008',
      productImage: '../assets/cookie/Cinnamon Bun Cookies.jpg',
      productName: 'Cinnamon Bun Cookies',
      productPrice: 30000,
      productDescription: 'Made with a delightful medley of ingredients that includes fragrant cinnamon, rich brown sugar, and a buttery cookie dough.',
      productCategory: 'Cookie',
    },
    {
      productId: 'PR009',
      productImage: '../assets/cookie/Cinnamon Oatmeal Cookies.jpg',
      productName: 'Cinnamon Oatmeal Cookies',
      productPrice: 30000,
      productDescription: 'Featuring a delightful combination of ingredients including hearty oats, aromatic cinnamon, and a touch of brown sugar.',
      productCategory: 'Cookie',
    },
    {
      productId: 'PR010',
      productImage: '../assets/cookie/Cinnamon White _ Dark Chocolate Chip Cookies.jpg',
      productName: 'Cinnamon White & Dark Chocolate Chip Cookies',
      productPrice: 35000,
      productDescription: 'Made with a heavenly blend of ingredients that includes aromatic cinnamon, luscious white and dark chocolate chips, and a buttery cookie dough.',
      productCategory: 'Cookie',
    },
    {
      productId: 'PR011',
      productImage: '../assets/cookie/French Toast Cookies.jpg',
      productName: 'French Toast Cookies',
      productPrice: 30000,
      productDescription: 'Featuring a medley of ingredients including warm cinnamon, rich maple syrup, and a buttery cookie base.',
      productCategory: 'Cookie',
    },
    {
      productId: 'PR012',
      productImage: '../assets/cookie/Snickerdoodles.jpg',
      productName: 'Snickerdoodles',
      productPrice: 35000,
      productDescription: 'Made with a simple yet irresistible combination of ingredients including creamy butter, fragrant cinnamon, and a touch of tangy cream of tartar.',
      productCategory: 'Cookie',
    },
    {
      productId: 'PR013',
      productImage: '../assets/tea/Cinnamon Apple Tea.jpg',
      productName: 'Cinnamon Apple Tea',
      productPrice: 20000,
      productDescription: 'Crafted with a harmonious combination of aromatic cinnamon and the natural sweetness of apples.',
      productCategory: 'Tea',
    },
    {
      productId: 'PR014',
      productImage: '../assets/tea/Cinnamon Ginger Tea.jpg',
      productName: 'Cinnamon Ginger Tea',
      productPrice: 25000,
      productDescription: 'Featuring the soothing essence of cinnamon and the zesty kick of ginger.',
      productCategory: 'Tea',
    },
    {
      productId: 'PR015',
      productImage: '../assets/tea/Cinnamon Spice Tea.jpg',
      productName: 'Cinnamon Spice Tea',
      productPrice: 25000,
      productDescription: 'Crafted with a blend of aromatic cinnamon, warming spices, and a hint of sweetness.',
      productCategory: 'Tea',
    },
    {
      productId: 'PR016',
      productImage: '../assets/coffee/Americano.png',
      productName: 'Americano',
      productPrice: 20000,
      productDescription: 'Crafted with a rich blend of espresso and hot water, creating a balanced and satisfying coffee beverage.',
      productCategory: 'Coffee',
    },
    {
      productId: 'PR017',
      productImage: '../assets/coffee/Cappucino.jpg',
      productName: 'Cappucino',
      productPrice: 30000,
      productDescription: 'Made with a perfect combination of rich espresso, creamy steamed milk, and a delicate layer of froth.',
      productCategory: 'Coffee',
    },
    {
      productId: 'PR018',
      productImage: '../assets/coffee/Latte.jpeg',
      productName: 'Latte',
      productPrice: 35000,
      productDescription: 'Crafted with a smooth blend of espresso and steamed milk, creating a luscious and velvety texture.',
      productCategory: 'Coffee',
    },
]